version: "3.8"
services:  
  nginx:
    image: nginx:1.23.2
    ports:
      - 20000:80
    volumes:
      - ${PWD}/loadBalancer-config/nginx.conf:/etc/nginx/nginx.conf
  
  app1:
    image: viktornginx-speciallog
    ports: 
      - 20001:80

  app2:
    image: nginx:1.23.2
    ports:
      - 20002:80